### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by qianqianluo**
fixed internal link for original English documentation

### CODE REVIEW

**Comment by woj-tek** [comment]
Looks ok, but please to update your branch first before making the PR because your changes restores some obsolete/remove documentation part (for example sections in `Tigase_Administration/Database_Management/Database_Preparation/MSSQL.inc`: https://github.com/tigase/tigase-server/pull/162/files#diff-e0750c200dabd32a72f6e5ee6f082920639df76a32b1abc54ea068084dd8e49fL151)

**Comment by qianqianluo** [comment]
here is what i did:
pull upstream (tigase-server) master to my local master branch. and then rebase to my documentation branch. and then i made some change. The changed you saw is the change i made after i rebase my branch. I made that change because i found the sphinx docs did not match asciidoc original documentation.

So I think it should be ready to merge.

**Comment by woj-tek** [comment]
Please always pull upstream and rebase your changes before making the pull request. As it seems, I still see removed bits of documentation in your pull request.

I remove jDTS information from documentation here: https://github.com/tigase/tigase-server/commit/70d414f7ad0b14522a755e43d6d0b80ce82e3d15#diff-e0750c200dabd32a72f6e5ee6f082920639df76a32b1abc54ea068084dd8e49f but your pull request reverts it: https://github.com/tigase/tigase-server/pull/162/files#diff-e0750c200dabd32a72f6e5ee6f082920639df76a32b1abc54ea068084dd8e49f.

**Comment by qianqianluo** [comment]
> Please always pull upstream and rebase your changes before making the pull request. As it seems, I still see removed bits of documentation in your pull request.
> 
> I remove jDTS information from documentation here: [70d414f#diff-e0750c200dabd32a72f6e5ee6f082920639df76a32b1abc54ea068084dd8e49f](https://github.com/tigase/tigase-server/commit/70d414f7ad0b14522a755e43d6d0b80ce82e3d15#diff-e0750c200dabd32a72f6e5ee6f082920639df76a32b1abc54ea068084dd8e49f) but your pull request reverts it: https://github.com/tigase/tigase-server/pull/162/files#diff-e0750c200dabd32a72f6e5ee6f082920639df76a32b1abc54ea068084dd8e49f.



> Please always pull upstream and rebase your changes before making the pull request. As it seems, I still see removed bits of documentation in your pull request.
> 
> I remove jDTS information from documentation here: [70d414f#diff-e0750c200dabd32a72f6e5ee6f082920639df76a32b1abc54ea068084dd8e49f](https://github.com/tigase/tigase-server/commit/70d414f7ad0b14522a755e43d6d0b80ce82e3d15#diff-e0750c200dabd32a72f6e5ee6f082920639df76a32b1abc54ea068084dd8e49f) but your pull request reverts it: https://github.com/tigase/tigase-server/pull/162/files#diff-e0750c200dabd32a72f6e5ee6f082920639df76a32b1abc54ea068084dd8e49f.

Sorry, my bad, when i cross-check with original docs in the website, i thought i did something wrong. i did not notice that change is what you made. I just revert the change/commit i did after i rebase. So now, it should be ready to merge back. After you merge to the master, i will do translation in weblate and push back to the master

**Pull request merged**
