### PR TITLE
fix issue: web browser complain bad message format if there are Chinese characters #18

### PR DESCRIPTION
**Pull request by towith**
refer to: https://github.com/tigase/tigase-server/issues/18

### CODE REVIEW

**Comment by woj-tek** [comment]
Hi, thank you for PR. In order for us to proceed with it we require "Source Code Disclaimer" - if you agree with it please submit a message stating that: "You submit your source code and allow Tigase to release the code as a part of Tigase's own software package under any license, either an open source or closed source."

**Comment by towith** [comment]
Sorry for just seeing this today,  I agree with this source code disclaimer ,  so where should I commit the disclaimer? If it is just in the email?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by towith** [comment]
@woj-tek  I submit my source code and allow Tigase to release the code as a part of Tigase's own software package under any license, either an open source or closed source

**Comment by woj-tek** [comment]
Thank you for the patch and Disclaimer. I reviewed it and have a couple of comments:
* Please add separate method that parses charset from `content_type` string;
* When parsing `content_type` string check if property is actually named `charset`
* Please add unit test for both methods using your example data.
* In exception log please use `Level.FINE`

**Comment by towith** [comment]
I have adopted my codes and make  amend commits to this pull request follow by your comments, please check again if the committed  would met,  thanks.

**Comment by woj-tek** [comment]
Thank you, looks better now. Could you update new file licence header by running `mvn license:format`? Alternatively you can either enable option "Enable edits from maintainers" or add header manually:
```
/*
 * Tigase XMPP Server - The instant messaging server
 * Copyright (C) 2004 Tigase, Inc. (office@tigase.com)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. Look for COPYING file in the top folder.
 * If not, see http://www.gnu.org/licenses/.
 */
```

**Comment by towith** [comment]
OK, i have add the license head to new file in this PR,  and i see checkbox before "Enable edits from maintainers" has already been checked.

**Comment by woj-tek** [comment]
Thank you, looks good now.

**Pull request merged**
